<?php

return [
    'cerulean'  => '/themes/cerulean/bulma.min.css',
    'clean'     => '/themes/clean/bulma.min.css',
    'cosmo'     => '/themes/cosmo/bulma.min.css',
    'cyborg'    => '/themes/cyborg/bulma.min.css',
    'darkly'    => '/themes/darkly/bulma.min.css',
    'flatly'    => '/themes/flatly/bulma.min.css',
    'journal'   => '/themes/journal/bulma.min.css',
    'litera'    => '/themes/litera/bulma.min.css',
    'lumen'     => '/themes/lumen/bulma.min.css',
    'lux'       => '/themes/lux/bulma.min.css',
    'materia'   => '/themes/materia/bulma.min.css',
    'minty'     => '/themes/minty/bulma.min.css',
    'pulse'     => '/themes/pulse/bulma.min.css',
    'sandstone' => '/themes/sandstone/bulma.min.css',
    'simplex'   => '/themes/simplex/bulma.min.css',
    'slate'     => '/themes/slate/bulma.min.css',
    'solar'     => '/themes/solar/bulma.min.css',
    'spacelab'  => '/themes/spacelab/bulma.min.css',
    'superhero' => '/themes/superhero/bulma.min.css',
    'united'    => '/themes/united/bulma.min.css',
    'yeti'      => '/themes/yeti/bulma.min.css',
];
