<?php

return [
    'generalSettings'     => 'General Settings',
    'reset'               => 'Reset',
    'language'            => 'Language',
    'startTutorial'       => 'Start Tutorial',
    'stateSave'           => 'Tables State Save',
    'fixed'               => 'Fixed layout',
    'collapse'            => 'Menu Collapse',
    'theme'               => 'Theme',
    'profile'             => 'Profile',
    'logout'              => 'Logout',
    'create'              => 'Create',
    'edit'                => 'Edit',
    'firstName'           => 'First Name',
    'lastName'            => 'Last Name',
    'phone'               => 'Phone',
    'email'               => 'Email',
    'no'                  => 'No',
    'yes'                 => 'Yes',
    'isActive'            => 'Is Active',
    'genericErrorMessage' => 'An error has occurred. The administrator has been notified. We are already working on fixing it.',
    'areYouSure'          => 'Are you sure?',
    'cancel'              => 'Cancel',
    'ok'                  => 'OK',
    'comments'            => 'Comments',
    'more'                => 'more',
    'documents'           => 'Documents',
    'contacts'            => 'Contacts',
    'totals'              => 'Totals',
    'emailReportRequest'  => 'The requested report was started. It can take a few minutes before you have it in your inbox',
    'successfulOperation' => 'The operation was successful',
    'savedChanges'        => 'The changes have been saved',
    'youHave'             => 'You have',
    'one'                 => 'unread notification',
    'many'                => 'unread notifications',
    'noNotifications'     => 'You don\'t have any unread notifications',
    'markAllAsRead'       => 'Mark All Read',
    'clearAll'            => 'Clear All',
    'notAuthorized'       => 'You are not authorized to perform this action',
];
